# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/msv/workspace/lib/c/c_procs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/msv/workspace/lib/c/c_procs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msv/workspace/lib/c/c_procs/CMakeFiles /home/msv/workspace/lib/c/c_procs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/msv/workspace/lib/c/c_procs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pthreadutils

# Build rule for target.
pthreadutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pthreadutils
.PHONY : pthreadutils

# fast build rule for target.
pthreadutils/fast:
	$(MAKE) -f CMakeFiles/pthreadutils.dir/build.make CMakeFiles/pthreadutils.dir/build
.PHONY : pthreadutils/fast

#=============================================================================
# Target rules for targets named cutils

# Build rule for target.
cutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cutils
.PHONY : cutils

# fast build rule for target.
cutils/fast:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/build
.PHONY : cutils/fast

#=============================================================================
# Target rules for targets named httputils

# Build rule for target.
httputils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 httputils
.PHONY : httputils

# fast build rule for target.
httputils/fast:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/build
.PHONY : httputils/fast

#=============================================================================
# Target rules for targets named netutils

# Build rule for target.
netutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 netutils
.PHONY : netutils

# fast build rule for target.
netutils/fast:
	$(MAKE) -f CMakeFiles/netutils.dir/build.make CMakeFiles/netutils.dir/build
.PHONY : netutils/fast

#=============================================================================
# Target rules for targets named test_strutils

# Build rule for target.
test_strutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_strutils
.PHONY : test_strutils

# fast build rule for target.
test_strutils/fast:
	$(MAKE) -f test/CMakeFiles/test_strutils.dir/build.make test/CMakeFiles/test_strutils.dir/build
.PHONY : test_strutils/fast

#=============================================================================
# Target rules for targets named test_daemon

# Build rule for target.
test_daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_daemon
.PHONY : test_daemon

# fast build rule for target.
test_daemon/fast:
	$(MAKE) -f test/CMakeFiles/test_daemon.dir/build.make test/CMakeFiles/test_daemon.dir/build
.PHONY : test_daemon/fast

#=============================================================================
# Target rules for targets named test_numutils

# Build rule for target.
test_numutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_numutils
.PHONY : test_numutils

# fast build rule for target.
test_numutils/fast:
	$(MAKE) -f test/CMakeFiles/test_numutils.dir/build.make test/CMakeFiles/test_numutils.dir/build
.PHONY : test_numutils/fast

#=============================================================================
# Target rules for targets named test_daemon_foreground

# Build rule for target.
test_daemon_foreground: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_daemon_foreground
.PHONY : test_daemon_foreground

# fast build rule for target.
test_daemon_foreground/fast:
	$(MAKE) -f test/CMakeFiles/test_daemon_foreground.dir/build.make test/CMakeFiles/test_daemon_foreground.dir/build
.PHONY : test_daemon_foreground/fast

#=============================================================================
# Target rules for targets named test_procspawn

# Build rule for target.
test_procspawn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_procspawn
.PHONY : test_procspawn

# fast build rule for target.
test_procspawn/fast:
	$(MAKE) -f test/CMakeFiles/test_procspawn.dir/build.make test/CMakeFiles/test_procspawn.dir/build
.PHONY : test_procspawn/fast

#=============================================================================
# Target rules for targets named test_procutils

# Build rule for target.
test_procutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_procutils
.PHONY : test_procutils

# fast build rule for target.
test_procutils/fast:
	$(MAKE) -f test/CMakeFiles/test_procutils.dir/build.make test/CMakeFiles/test_procutils.dir/build
.PHONY : test_procutils/fast

src/daemonutils.o: src/daemonutils.c.o

.PHONY : src/daemonutils.o

# target to build an object file
src/daemonutils.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/daemonutils.c.o
.PHONY : src/daemonutils.c.o

src/daemonutils.i: src/daemonutils.c.i

.PHONY : src/daemonutils.i

# target to preprocess a source file
src/daemonutils.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/daemonutils.c.i
.PHONY : src/daemonutils.c.i

src/daemonutils.s: src/daemonutils.c.s

.PHONY : src/daemonutils.s

# target to generate assembly for a file
src/daemonutils.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/daemonutils.c.s
.PHONY : src/daemonutils.c.s

src/fileutils.o: src/fileutils.c.o

.PHONY : src/fileutils.o

# target to build an object file
src/fileutils.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/fileutils.c.o
.PHONY : src/fileutils.c.o

src/fileutils.i: src/fileutils.c.i

.PHONY : src/fileutils.i

# target to preprocess a source file
src/fileutils.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/fileutils.c.i
.PHONY : src/fileutils.c.i

src/fileutils.s: src/fileutils.c.s

.PHONY : src/fileutils.s

# target to generate assembly for a file
src/fileutils.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/fileutils.c.s
.PHONY : src/fileutils.c.s

src/httputils/httpsrvutils.o: src/httputils/httpsrvutils.c.o

.PHONY : src/httputils/httpsrvutils.o

# target to build an object file
src/httputils/httpsrvutils.c.o:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/httpsrvutils.c.o
.PHONY : src/httputils/httpsrvutils.c.o

src/httputils/httpsrvutils.i: src/httputils/httpsrvutils.c.i

.PHONY : src/httputils/httpsrvutils.i

# target to preprocess a source file
src/httputils/httpsrvutils.c.i:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/httpsrvutils.c.i
.PHONY : src/httputils/httpsrvutils.c.i

src/httputils/httpsrvutils.s: src/httputils/httpsrvutils.c.s

.PHONY : src/httputils/httpsrvutils.s

# target to generate assembly for a file
src/httputils/httpsrvutils.c.s:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/httpsrvutils.c.s
.PHONY : src/httputils/httpsrvutils.c.s

src/httputils/mimetypes.o: src/httputils/mimetypes.c.o

.PHONY : src/httputils/mimetypes.o

# target to build an object file
src/httputils/mimetypes.c.o:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/mimetypes.c.o
.PHONY : src/httputils/mimetypes.c.o

src/httputils/mimetypes.i: src/httputils/mimetypes.c.i

.PHONY : src/httputils/mimetypes.i

# target to preprocess a source file
src/httputils/mimetypes.c.i:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/mimetypes.c.i
.PHONY : src/httputils/mimetypes.c.i

src/httputils/mimetypes.s: src/httputils/mimetypes.c.s

.PHONY : src/httputils/mimetypes.s

# target to generate assembly for a file
src/httputils/mimetypes.c.s:
	$(MAKE) -f CMakeFiles/httputils.dir/build.make CMakeFiles/httputils.dir/src/httputils/mimetypes.c.s
.PHONY : src/httputils/mimetypes.c.s

src/netutils/netutils.o: src/netutils/netutils.c.o

.PHONY : src/netutils/netutils.o

# target to build an object file
src/netutils/netutils.c.o:
	$(MAKE) -f CMakeFiles/netutils.dir/build.make CMakeFiles/netutils.dir/src/netutils/netutils.c.o
.PHONY : src/netutils/netutils.c.o

src/netutils/netutils.i: src/netutils/netutils.c.i

.PHONY : src/netutils/netutils.i

# target to preprocess a source file
src/netutils/netutils.c.i:
	$(MAKE) -f CMakeFiles/netutils.dir/build.make CMakeFiles/netutils.dir/src/netutils/netutils.c.i
.PHONY : src/netutils/netutils.c.i

src/netutils/netutils.s: src/netutils/netutils.c.s

.PHONY : src/netutils/netutils.s

# target to generate assembly for a file
src/netutils/netutils.c.s:
	$(MAKE) -f CMakeFiles/netutils.dir/build.make CMakeFiles/netutils.dir/src/netutils/netutils.c.s
.PHONY : src/netutils/netutils.c.s

src/procspawn.o: src/procspawn.c.o

.PHONY : src/procspawn.o

# target to build an object file
src/procspawn.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procspawn.c.o
.PHONY : src/procspawn.c.o

src/procspawn.i: src/procspawn.c.i

.PHONY : src/procspawn.i

# target to preprocess a source file
src/procspawn.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procspawn.c.i
.PHONY : src/procspawn.c.i

src/procspawn.s: src/procspawn.c.s

.PHONY : src/procspawn.s

# target to generate assembly for a file
src/procspawn.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procspawn.c.s
.PHONY : src/procspawn.c.s

src/procutils.o: src/procutils.c.o

.PHONY : src/procutils.o

# target to build an object file
src/procutils.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procutils.c.o
.PHONY : src/procutils.c.o

src/procutils.i: src/procutils.c.i

.PHONY : src/procutils.i

# target to preprocess a source file
src/procutils.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procutils.c.i
.PHONY : src/procutils.c.i

src/procutils.s: src/procutils.c.s

.PHONY : src/procutils.s

# target to generate assembly for a file
src/procutils.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/procutils.c.s
.PHONY : src/procutils.c.s

src/pthreadutils/thrdpool.o: src/pthreadutils/thrdpool.c.o

.PHONY : src/pthreadutils/thrdpool.o

# target to build an object file
src/pthreadutils/thrdpool.c.o:
	$(MAKE) -f CMakeFiles/pthreadutils.dir/build.make CMakeFiles/pthreadutils.dir/src/pthreadutils/thrdpool.c.o
.PHONY : src/pthreadutils/thrdpool.c.o

src/pthreadutils/thrdpool.i: src/pthreadutils/thrdpool.c.i

.PHONY : src/pthreadutils/thrdpool.i

# target to preprocess a source file
src/pthreadutils/thrdpool.c.i:
	$(MAKE) -f CMakeFiles/pthreadutils.dir/build.make CMakeFiles/pthreadutils.dir/src/pthreadutils/thrdpool.c.i
.PHONY : src/pthreadutils/thrdpool.c.i

src/pthreadutils/thrdpool.s: src/pthreadutils/thrdpool.c.s

.PHONY : src/pthreadutils/thrdpool.s

# target to generate assembly for a file
src/pthreadutils/thrdpool.c.s:
	$(MAKE) -f CMakeFiles/pthreadutils.dir/build.make CMakeFiles/pthreadutils.dir/src/pthreadutils/thrdpool.c.s
.PHONY : src/pthreadutils/thrdpool.c.s

src/strutils.o: src/strutils.c.o

.PHONY : src/strutils.o

# target to build an object file
src/strutils.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/strutils.c.o
.PHONY : src/strutils.c.o

src/strutils.i: src/strutils.c.i

.PHONY : src/strutils.i

# target to preprocess a source file
src/strutils.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/strutils.c.i
.PHONY : src/strutils.c.i

src/strutils.s: src/strutils.c.s

.PHONY : src/strutils.s

# target to generate assembly for a file
src/strutils.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/strutils.c.s
.PHONY : src/strutils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pthreadutils"
	@echo "... cutils"
	@echo "... httputils"
	@echo "... netutils"
	@echo "... test"
	@echo "... test_strutils"
	@echo "... test_daemon"
	@echo "... test_numutils"
	@echo "... test_daemon_foreground"
	@echo "... test_procspawn"
	@echo "... test_procutils"
	@echo "... src/daemonutils.o"
	@echo "... src/daemonutils.i"
	@echo "... src/daemonutils.s"
	@echo "... src/fileutils.o"
	@echo "... src/fileutils.i"
	@echo "... src/fileutils.s"
	@echo "... src/httputils/httpsrvutils.o"
	@echo "... src/httputils/httpsrvutils.i"
	@echo "... src/httputils/httpsrvutils.s"
	@echo "... src/httputils/mimetypes.o"
	@echo "... src/httputils/mimetypes.i"
	@echo "... src/httputils/mimetypes.s"
	@echo "... src/netutils/netutils.o"
	@echo "... src/netutils/netutils.i"
	@echo "... src/netutils/netutils.s"
	@echo "... src/procspawn.o"
	@echo "... src/procspawn.i"
	@echo "... src/procspawn.s"
	@echo "... src/procutils.o"
	@echo "... src/procutils.i"
	@echo "... src/procutils.s"
	@echo "... src/pthreadutils/thrdpool.o"
	@echo "... src/pthreadutils/thrdpool.i"
	@echo "... src/pthreadutils/thrdpool.s"
	@echo "... src/strutils.o"
	@echo "... src/strutils.i"
	@echo "... src/strutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

